# Iris Flower Classification

In [36]:
import pandas as pd
import matplotlib.pyplot as plt

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/IRIS.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [39]:
# end of dataset; 150 rows of data
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

## About Dataset
### Context

The Iris flower data set is a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems. It is sometimes called Anderson's Iris data set because Edgar Anderson collected the data to quantify the morphologic variation of Iris flowers of three related species. The data set consists of 50 samples from each of three species of Iris (Iris Setosa, Iris virginica, and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

This dataset became a typical test case for many statistical classification techniques in machine learning such as support vector machines

### Content
- The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).

####  Acknowledgements
This dataset is free and is publicly available at the UCI Machine Learning Repository.

In [40]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [41]:
print(df['species'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

### Model

In [42]:
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [81]:
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()

In [82]:
x = df.drop('species', axis=1)
y = df['species']

### KNN

In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)

preds = knn.predict(x_test)

In [110]:
accuracy = knn.score(x_test, y_test)
print(accuracy)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, preds)
cm

1.0

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]])

In [111]:
x_test_new = np.array([[6.5, 3.1, 5.3, 1.5]])
pred = knn.predict(x_test_new)
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names

array(['Iris-virginica'], dtype=object)

In [112]:
x_test_new = np.array([[3.5, 1.1, 3.3, 2.2]])
pred = knn.predict(x_test_new)
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names

array(['Iris-versicolor'], dtype=object)

### Naive bayes classifier

In [113]:
# naive bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
model_preds = model.predict(x_test)
# print(list(model_preds))

In [114]:
accuracy = model.score(x_test, y_test)
print(accuracy)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, model_preds)
cm

0.9666666666666667

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  5]])

In [115]:
x_test_new = np.array([[6.5, 3.1, 5.3, 1.5]])
pred = model.predict(x_test_new)
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but GaussianNB was fitted with feature names

array(['Iris-virginica'], dtype='<U15')

In [116]:
x_test_new = np.array([[3.5, 1.1, 3.3, 2.2]])
pred = model.predict(x_test_new)
pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but GaussianNB was fitted with feature names

array(['Iris-versicolor'], dtype='<U15')